# This is a test pipeline for the API tests
name: API Benchmark Tests
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: Select the environment to execute on
        type: choice 
        options: 
          - ops
          - uat
      runtime:
        required: true
        description: Define how long the benchmarking should last. Examples 5s, 2m, 1h 3m 
        default: 10s
        type: string 
      threadcount:
        required: true
        description: Select how many times the tests should run at the same time
        default: 1
        type: number
      

jobs:
  # First job in the workflow installs and verifies the software
  build:
    name: Test Execution
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it and the directory won't be empty
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install -r ./dependencies_pip
      - name: Execute tests
        run: |
          sh run_local.sh "${{ github.event.inputs.environment }}" "${{ github.event.inputs.runtime }}" "${{ github.event.inputs.threadcount }}"
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            test-results/**/*.index
      - name: ANY REPROT - GH Pages Push - SAME REPO
        uses: PavanMudigonda/html-reporter-github-pages@v1.2
        with:
          test_results: locust_tests_report
          keep_reports: 10
          subfolder: test-results  # Level 1 Folder Structure you like
          tool_name:  # Level 2 Folder Structure you like
          workflow_name:   # Level 3 Folder Structure you like
          env:   # Level 4 Folder Structure you like
